catalog: use public hostname in config when using self-signed SSL behind real SSL from pagekite
Fix magpie connection error like:

```
<ows:ExceptionText>Process error: method=wps_pavicrawler.py._handler, line=146, msg=Traceback (most recent call last):
  File &#34;/usr/local/lib/python2.7/dist-packages/pavics_datacatalog-0.6.11-py2.7.egg/pavics_datacatalog/wps_processes/wps_pavicrawler.py&#34;, line 125, in _handler
    verify=self.verify)
  File &#34;/usr/lib/python2.7/dist-packages/requests/sessions.py&#34;, line 523, in post
    return self.request(&#39;POST&#39;, url, data=data, json=json, **kwargs)
  File &#34;/usr/lib/python2.7/dist-packages/requests/sessions.py&#34;, line 480, in request
    resp = self.send(prep, **send_kwargs)
  File &#34;/usr/lib/python2.7/dist-packages/requests/sessions.py&#34;, line 588, in send
    r = adapter.send(request, **kwargs)
  File &#34;/usr/lib/python2.7/dist-packages/requests/adapters.py&#34;, line 447, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
</ows:ExceptionText>
```

Thredds url need to use the public hostname too so the path recorded in Solr is
the good public one.

The wms_alternate_server, not sure what it impact but looks like it might be
useful so change it too.