deploy raven testdata cronjob: yml config file path has to exist on host due to volume mount
Fix following error:

+ docker run --rm --name deploy_data_yq -v /deploy-data-raven-testdata-to-thredds.yml:/deploy-data-raven-testdata-to-thredds.yml:ro mikefarah/yq:3.3.4 yq r -p v /deploy-data-raven-testdata-to-thredds.yml '[*].repo_url'
Error: yaml: input error: read /deploy-data-raven-testdata-to-thredds.yml: is a directory