generic_bird: fix wrong postgres_generic_bird credentials
Missing template explansion and wrong credential file.

`docker logs generic_bird` had this error
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres_generic_bird" (172.23.0.20), port 5432 failed: FATAL:  database "generic_bird" does not exist
```