deploy-data: additional error checking for git clone and fetch that require credentials
+ git fetch --prune --all
Fetching origin
Host key verification failed.^M
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
+ echo 'git fetch failed'
git fetch failed
+ exit 1