tests: fix random error on some hosts only
Fix the errors below:

============================= test session starts ==============================
platform linux -- Python 3.11.4, pytest-7.2.2, pluggy-1.0.0
rootdir: /repos/birdhouse-deploy-WIP
collected 13 items

tests/test_read_configs_include.py .FF.F.FF.F.FF                         [100%]

=================================== FAILURES ===================================
____________________ TestReadConfigs.test_all_conf_dirs_set ____________________

self = <test_read_configs_include.TestReadConfigs object at 0x7f45a77b3750>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_all_conf_dirs_set(self, read_config_include_file) -> None:
        """Test that the ALL_CONF_DIRS variable is set"""
        proc = self.run_func(read_config_include_file, {}, 'echo "$ALL_CONF_DIRS"')
        print(proc.stdout)  # useful when assert fail
>       assert get_command_stdout(proc).strip()
E       AssertionError: assert ''
E        +  where '' = <built-in method strip of str object at 0x7f45a77cc470>()
E        +    where <built-in method strip of str object at 0x7f45a77cc470> = '\n\n'.strip
E        +      where '\n\n' = get_command_stdout(CompletedProcess(args='. /repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh && read_configs && echo ...store/repos/birdhouse-deploy-WIP\nUsing local environment file at: /tmp/tmpa6fffa6a\n#env for testing#\n\n', stderr=''))

tests/test_read_configs_include.py:116: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
Using local environment file at: /tmp/tmpa6fffa6a
/repos/birdhouse-deploy-WIP
Using local environment file at: /tmp/tmpa6fffa6a

_______________ TestReadConfigs.test_all_conf_dirs_default_order _______________

self = <test_read_configs_include.TestReadConfigs object at 0x7f45a77b3e10>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_all_conf_dirs_default_order(self, read_config_include_file) -> None:
        """Test that the expected order that default.env files are loaded is correct"""
        proc = self.run_func(read_config_include_file, {}, 'echo "$ALL_CONF_DIRS"')
        print(proc.stdout)  # useful when assert fail
>       assert split_and_strip(get_command_stdout(proc)) == self.default_all_conf_order
E       AssertionError: assert [] == ['./config/pr...leefowl', ...]
E         Right contains 23 more items, first extra item: './config/proxy'
E         Use -v to get more diff

tests/test_read_configs_include.py:123: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
Using local environment file at: /tmp/tmp6z8tjeb6
/repos/birdhouse-deploy-WIP
Using local environment file at: /tmp/tmp6z8tjeb6

________________ TestReadConfigs.test_dependencies_loaded_first ________________

self = <test_read_configs_include.TestReadConfigs object at 0x7f45a77c4cd0>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_dependencies_loaded_first(self, read_config_include_file) -> None:
        """Test that dependencies are loaded first"""
        extra = {"EXTRA_CONF_DIRS": '"./optional-components/test-weaver"'}
        proc = self.run_func(read_config_include_file, extra, 'echo "$ALL_CONF_DIRS"')
        print(proc.stdout)  # useful when assert fail
>       assert split_and_strip(get_command_stdout(proc))[-2:] == [
            "./components/weaver",
            "./optional-components/test-weaver",
        ]
E       AssertionError: assert ['./optional-.../test-weaver'] == ['./component.../test-weaver']
E         At index 0 diff: './optional-components/test-weaver' != './components/weaver'
E         Right contains one more item: './optional-components/test-weaver'
E         Use -v to get more diff

tests/test_read_configs_include.py:140: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
Using local environment file at: /tmp/tmplo58uftq
/repos/birdhouse-deploy-WIP
Using local environment file at: /tmp/tmplo58uftq

        ./optional-components/test-weaver

_______________ TestReadConfigs.test_delayed_eval_default_value ________________

self = <test_read_configs_include.TestReadConfigs object at 0x7f45a77c5b10>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_delayed_eval_default_value(self, read_config_include_file) -> None:
        """Test delayed eval when value not set in env.local"""
        extra = {"PAVICS_FQDN": '"fqdn.example.com"'}
        proc = self.run_func(read_config_include_file, extra,
                             'echo "$PAVICS_FQDN_PUBLIC - $JUPYTERHUB_USER_DATA_DIR - $GEOSERVER_DATA_DIR"')
        print(proc.stdout)  # useful when assert fail
        # By default, PAVICS_FQDN_PUBLIC has same value as PAVICS_FQDN.
>       assert (split_and_strip(get_command_stdout(proc))[-1] ==
                "fqdn.example.com - /data/jupyterhub_user_data - /data/geoserver")
E       AssertionError: assert '- /data/jupy...ata/geoserver' == 'fqdn.example...ata/geoserver'
E         - fqdn.example.com - /data/jupyterhub_user_data - /data/geoserver
E         ? -----------------
E         + - /data/jupyterhub_user_data - /data/geoserver

tests/test_read_configs_include.py:159: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
Using local environment file at: /tmp/tmp1tjl5kuq
/repos/birdhouse-deploy-WIP
Using local environment file at: /tmp/tmp1tjl5kuq
 - /data/jupyterhub_user_data - /data/geoserver

________________ TestReadConfigs.test_delayed_eval_custom_value ________________

self = <test_read_configs_include.TestReadConfigs object at 0x7f45a77c6210>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_delayed_eval_custom_value(self, read_config_include_file) -> None:
        """Test delayed eval when value is set in env.local"""
        extra = {"PAVICS_FQDN": '"fqdn.example.com"',
                 "PAVICS_FQDN_PUBLIC": '"public.example.com"',
                 "DATA_PERSIST_ROOT": '"/my-data-root"',  # indirectly change JUPYTERHUB_USER_DATA_DIR
                 "GEOSERVER_DATA_DIR": '"/my-geoserver-data"',
                 }
        proc = self.run_func(read_config_include_file, extra,
                             'echo "$PAVICS_FQDN_PUBLIC - $JUPYTERHUB_USER_DATA_DIR - $GEOSERVER_DATA_DIR"')
        print(proc.stdout)  # useful when assert fail
        # If PAVICS_FQDN_PUBLIC is set in env.local, that value should be effective.
>       assert (split_and_strip(get_command_stdout(proc))[-1] ==
                "public.example.com - /my-data-root/jupyterhub_user_data - /my-geoserver-data")
E       AssertionError: assert 'public.examp...eoserver-data' == 'public.examp...eoserver-data'
E         - public.example.com - /my-data-root/jupyterhub_user_data - /my-geoserver-data
E         ?                       ---    -----
E         + public.example.com - /data/jupyterhub_user_data - /my-geoserver-data

tests/test_read_configs_include.py:174: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
Using local environment file at: /tmp/tmp001vbau5
/repos/birdhouse-deploy-WIP
Using local environment file at: /tmp/tmp001vbau5
public.example.com - /data/jupyterhub_user_data - /my-geoserver-data

_____________ TestCreateComposeConfList.test_compose_no_overrides ______________

self = <test_read_configs_include.TestCreateComposeConfList object at 0x7f45a77c70d0>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_compose_no_overrides(self, read_config_include_file):
        """Test that COMPOSE_CONF_LIST is set correctly when there are no overrides"""
        proc = self.run_func(
            read_config_include_file, {"ALL_CONF_DIRS": "./config/finch ./config/raven"}, 'echo "$COMPOSE_CONF_LIST"'
        )
        print(proc.stdout)  # useful when assert fail
>       assert split_and_strip(get_command_stdout(proc), split_on="-f") == [
            "docker-compose.yml",
            "./config/finch/docker-compose-extra.yml",
            "./config/raven/docker-compose-extra.yml",
        ]
E       AssertionError: assert ['docker-compose.yml'] == ['docker-comp...se-extra.yml']
E         Right contains 2 more items, first extra item: './config/finch/docker-compose-extra.yml'
E         Use -v to get more diff

tests/test_read_configs_include.py:280: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
/repos/birdhouse-deploy-WIP
-f docker-compose.yml

_______________ TestCreateComposeConfList.test_compose_overrides _______________

self = <test_read_configs_include.TestCreateComposeConfList object at 0x7f45a77c7ed0>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_compose_overrides(self, read_config_include_file):
        """Test that COMPOSE_CONF_LIST is set correctly when there are overrides"""
        proc = self.run_func(
            read_config_include_file, {"ALL_CONF_DIRS": "./config/finch ./config/magpie"}, 'echo "$COMPOSE_CONF_LIST"'
        )
        print(proc.stdout)  # useful when assert fail
>       assert split_and_strip(get_command_stdout(proc), split_on="-f") == [
            "docker-compose.yml",
            "./config/finch/docker-compose-extra.yml",
            "./config/magpie/docker-compose-extra.yml",
            "./config/finch/config/magpie/docker-compose-extra.yml",
        ]
E       AssertionError: assert ['docker-compose.yml'] == ['docker-comp...se-extra.yml']
E         Right contains 3 more items, first extra item: './config/finch/docker-compose-extra.yml'
E         Use -v to get more diff

tests/test_read_configs_include.py:305: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
/repos/birdhouse-deploy-WIP
-f docker-compose.yml

_____________ TestCreateComposeConfList.test_default_all_conf_dirs _____________

self = <test_read_configs_include.TestCreateComposeConfList object at 0x7f45a77cc5d0>
read_config_include_file = '/repos/birdhouse-deploy-WIP/birdhouse/read-configs.include.sh'

    @pytest.mark.usefixtures("run_in_compose_dir")
    def test_default_all_conf_dirs(self, read_config_include_file):
        proc = self.run_func(
            read_config_include_file,
            {"ALL_CONF_DIRS": " ".join(TestReadConfigs.default_all_conf_order)},
            'echo "$COMPOSE_CONF_LIST"',
        )
        print(proc.stdout)  # useful when assert fail
>       assert split_and_strip(get_command_stdout(proc), split_on="-f") == self.default_conf_list_order
E       AssertionError: assert ['docker-compose.yml'] == ['docker-comp...tra.yml', ...]
E         Right contains 66 more items, first extra item: './config/proxy/docker-compose-extra.yml'
E         Use -v to get more diff

tests/test_read_configs_include.py:320: AssertionError
----------------------------- Captured stdout call -----------------------------
/repos/birdhouse-deploy/birdhouse
/repos/birdhouse-deploy-WIP
-f docker-compose.yml

=========================== short test summary info ============================
FAILED tests/test_read_configs_include.py::TestReadConfigs::test_all_conf_dirs_set
FAILED tests/test_read_configs_include.py::TestReadConfigs::test_all_conf_dirs_default_order
FAILED tests/test_read_configs_include.py::TestReadConfigs::test_dependencies_loaded_first
FAILED tests/test_read_configs_include.py::TestReadConfigs::test_delayed_eval_default_value
FAILED tests/test_read_configs_include.py::TestReadConfigs::test_delayed_eval_custom_value
FAILED tests/test_read_configs_include.py::TestCreateComposeConfList::test_compose_no_overrides
FAILED tests/test_read_configs_include.py::TestCreateComposeConfList::test_compose_overrides
FAILED tests/test_read_configs_include.py::TestCreateComposeConfList::test_default_all_conf_dirs
========================= 8 failed, 5 passed in 0.40s ==========================